# Generated by Django 3.2.12 on 2024-06-05 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept_Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], max_length=10)),
                ('no_participants', models.IntegerField()),
                ('description', models.TextField()),
                ('from_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('date_to', models.DateField()),
                ('time_to', models.TimeField()),
                ('brochure', models.ImageField(upload_to='brochures/')),
                ('dept_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.dept_club')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], max_length=10)),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('designation', models.CharField(max_length=100)),
                ('dept_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.dept_club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('report', models.TextField(null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='event_reports/photos/')),
                ('alternate_photo', models.ImageField(blank=True, null=True, upload_to='event_reports/alternate_photos/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='event.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='event.tags'),
        ),
        migrations.CreateModel(
            name='duty_alloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.dept_club')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.faculty')),
            ],
        ),
    ]
