# Generated by Django 3.2.12 on 2024-06-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='Event',
            new_name='event',
        ),
        migrations.AlterField(
            model_name='permission',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
    ]
