# Generated by Django 3.2.12 on 2024-06-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20240609_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='event',
            new_name='Event',
        ),
        migrations.AlterField(
            model_name='permission',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], max_length=10),
        ),
    ]
