# Generated by Django 3.2.12 on 2024-06-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20240609_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_report',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
